In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', 20)

## Customer Data

In [ ]:
df_cus = pd.read_json(r"../data/raw/customer_data.json")
df_cus[:10]

,customer_id,full_name,email,phone,gender,date_of_birth,city,occupation,membership_tier,lifetime_value,total_orders,is_active,joined_date,last_purchase_date,preferred_category
0,CUST01100,Customer_1100,customer1100@gmail.com,+91-9042480121,Other,2001-05-04,Surat,Teacher,Gold,37700.71,56,False,2023-08-07,2024-07-29,Sports
1,CUST01694,Customer_1694,customer1694@gmail.com,+91-7298829927,Male,1983-01-12,Mumbai,Government Employee,Silver,34961.74,177,True,2020-08-23,2024-05-30,Sports
2,CUST00104,Customer_104,customer104@gmail.com,+91-9507694884,Male,1986-06-19,None,Business Owner,SILVER,35803.28,129,False,2021-09-29,2024-05-24,Electronics
3,CUST01532,Customer_1532,customer1532@gmail.com,+91-8485059977,Other,2001-05-14,Pune,Student,Platinum,35649.59,20,True,2019-09-02,None,Furniture
4,CUST01970,Customer_1970,customer1970@gmail.com,+91-7975175423,Female,1985-12-14,Jaipur,Student,BRONZE,21719.53,89,True,2020-05-17,2024-06-27,Toys
5,CUST00802,Customer_802,customer802@gmail.com,+91-9548886614,Male,1969-10-05,Delhi,Teacher,PLATINUM,45186.68,116,False,2023-07-18,2024-10-12,Toys
6,CUST01431,Customer_1431,customer1431@yahoo.com,+91-8837782194,Male,2000-09-12,Bangalore,Teacher,Gold,8573.01,83,True,2019-07-10,2024-12-04,Toys
7,CUST00781,Customer_781,customer781@yahoo.com,+91-9681184477,male,1993-06-24,Surat,Freelancer,Gold,10350.63,13,True,2021-10-12,2024-04-08,Toys
8,CUST01231,Customer_1231,customer1231@yahoo.com,+91-8408654725,Other,1995-12-03,Kolkata,Engineer,Silver,24147.76,154,True,2020-09-17,2024-12-25,Groceries
9,CUST01678,Customer_1678,customer1678@gmail.com,+91-9744517243,Other,2003-02-13,Hyderabad,Freelancer,Platinum,18134.28,89,True,2020-09-02,2024-09-17,Toys

In [3]:
df_cus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2060 entries, 0 to 2059
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         2060 non-null   object
 1   full_name           2060 non-null   object
 2   email               1938 non-null   object
 3   phone               1937 non-null   object
 4   gender              2060 non-null   object
 5   date_of_birth       2060 non-null   object
 6   city                1938 non-null   object
 7   occupation          1938 non-null   object
 8   membership_tier     2060 non-null   object
 9   lifetime_value      2060 non-null   object
 10  total_orders        2060 non-null   int64
 11  is_active           2060 non-null   bool
 12  joined_date         2060 non-null   object
 13  last_purchase_date  1934 non-null   object
 14  preferred_category  2060 non-null   object
dtypes: bool(1), int64(1), object(13)
memory usage: 227.4+ KB

### Validation of Mail and phone number

In [4]:
# Phone validation
df_cus['phone_clean'] = df_cus['phone'].str.replace(r'[\s-]', '', regex=True)
phone_no_pattern = r'^(\+91)?[6-9]\d{9}$'
df_cus['valid_phone'] = df_cus['phone_clean'].str.match(
    phone_no_pattern,
    na=False
)
df_cus['valid_phone'].value_counts()

valid_phone
True     1937
False     123
Name: count, dtype: int64

In [5]:
email_pattern = r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
df_cus['valid_email'] = df_cus['email'].str.match(
    email_pattern,
    na=False
)

df_cus['valid_email'].value_counts()

valid_email
True     1938
False     122
Name: count, dtype: int64

In [6]:
df_cus[~df_cus['valid_email']]

,customer_id,full_name,email,phone,gender,date_of_birth,city,occupation,membership_tier,lifetime_value,total_orders,is_active,joined_date,last_purchase_date,preferred_category,phone_clean,valid_phone,valid_email
26,CUST00488,Customer_488,None,+91-8638631521,Female,1994-12-21,Delhi,Doctor,Platinum,48112.0,148,True,2023-02-01,2024-04-17,Groceries,+918638631521,True,False
31,CUST01370,Customer_1370,None,+91-7029045484,Male,1990-03-02,Chennai,Engineer,Silver,4267.29,17,False,2022-04-28,2024-02-17,Furniture,+917029045484,True,False
59,CUST00650,Customer_650,None,None,Male,1965-05-14,Jaipur,Government Employee,Bronze,32870.87,85,False,2020-09-17,2024-07-22,Furniture,None,False,False
63,CUST00328,Customer_328,None,+91-7242946259,Female,1973-07-17,Bangalore,Engineer,Gold,45418.81,59,False,2019-02-27,None,Electronics,+917242946259,True,False
72,CUST00318,Customer_318,None,+91-9655310449,Other,1986-03-28,Jaipur,Freelancer,Bronze,24406.87,37,False,2020-01-31,2024-02-10,Groceries,+919655310449,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1898,CUST00900,Customer_900,None,+91-8874136566,Other,15-11-2005,Surat,Business Owner,Silver,17843.95,34,False,2022-11-02,2024-01-03,Groceries,+918874136566,True,False
1995,CUST00272,Customer_272,None,+91-9457434739,male,1986-11-14,Chennai,Government Employee,Platinum,45693.89,174,True,2020-05-10,2024-12-12,Clothing,+919457434739,True,False
2020,CUST01842,Customer_1842,None,+91-8896486885,Other,1978-06-27,Chennai,Retired,Platinum,21445.48,14,False,2022-08-16,None,Sports,+918896486885,True,False
2022,CUST00602,Customer_602,None,+91-9697376962,Other,1982-12-01,Hyderabad,Retired,Platinum,48565.41,88,True,2022-11-01,2024-09-11,Electronics,+919697376962,True,False
2048,CUST01251,Customer_1251,None,+91-7203003436,Other,1990-11-27,Kolkata,Business Owner,Platinum,3207.21,96,False,2019-11-24,2024-11-12,Groceries,+917203003436,True,False

In [7]:
df_cus[~df_cus['valid_phone']]

,customer_id,full_name,email,phone,gender,date_of_birth,city,occupation,membership_tier,lifetime_value,total_orders,is_active,joined_date,last_purchase_date,preferred_category,phone_clean,valid_phone,valid_email
11,CUST01877,Customer_1877,customer1877@yahoo.com,None,Other,2004-10-02,Chennai,Business Owner,Gold,2477.79,52,True,2021-02-12,2024-08-29,Sports,None,False,True
13,CUST01040,Customer_1040,customer1040@gmail.com,None,Other,1964-09-18,Jaipur,Student,Bronze,24792.72,183,False,2020-02-28,2024-04-12,Toys,None,False,True
23,CUST01903,Customer_1903,customer1903@yahoo.com,None,Male,2000-03-24,Pune,Student,Platinum,31448.09,180,False,2021-10-14,2024-05-13,Clothing,None,False,True
34,CUST01085,Customer_1085,customer1085@yahoo.com,None,Other,1996-11-17,Delhi,Engineer,Bronze,19960.85,72,True,2020-04-02,2024-03-21,Clothing,None,False,True
44,CUST01801,Customer_1801,customer1801@yahoo.com,None,Female,1981-03-25,Pune,None,Platinum,28551.52,54,True,2020-10-29,2024-05-24,Electronics,None,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987,CUST00851,Customer_851,customer851@yahoo.com,None,Other,1972-02-05,Ahmedabad,Doctor,SILVER,13387.79,153,False,2021-06-19,2024-12-05,Clothing,None,False,True
1988,CUST01568,Customer_1568,customer1568@gmail.com,None,Male,1969-09-16,Surat,None,Platinum,$49962.09,110,True,2021-01-09,2024-07-07,Clothing,None,False,True
2041,CUST01828,Customer_1828,customer1828@gmail.com,None,Female,08-06-1978,Chennai,Government Employee,Platinum,$25158.43,174,True,2022-11-19,2024-07-09,Groceries,None,False,True
2042,CUST00388,Customer_388,customer388@gmail.com,None,Male,1980-07-25,Delhi,Engineer,Silver,$31451.44,112,True,2019-05-02,2024-09-04,Sports,None,False,True
2045,CUST00564,Customer_564,customer564@gmail.com,None,Female,1969-11-25,Pune,Government Employee,Bronze,44635.98,72,True,2023-04-30,2024-01-12,Toys,None,False,True

In [8]:
df_cus = df_cus.drop(['valid_phone', 'valid_email','phone_clean'], axis=1)
df_cus

,customer_id,full_name,email,phone,gender,date_of_birth,city,occupation,membership_tier,lifetime_value,total_orders,is_active,joined_date,last_purchase_date,preferred_category
0,CUST01100,Customer_1100,customer1100@gmail.com,+91-9042480121,Other,2001-05-04,Surat,Teacher,Gold,37700.71,56,False,2023-08-07,2024-07-29,Sports
1,CUST01694,Customer_1694,customer1694@gmail.com,+91-7298829927,Male,1983-01-12,Mumbai,Government Employee,Silver,34961.74,177,True,2020-08-23,2024-05-30,Sports
2,CUST00104,Customer_104,customer104@gmail.com,+91-9507694884,Male,1986-06-19,None,Business Owner,SILVER,35803.28,129,False,2021-09-29,2024-05-24,Electronics
3,CUST01532,Customer_1532,customer1532@gmail.com,+91-8485059977,Other,2001-05-14,Pune,Student,Platinum,35649.59,20,True,2019-09-02,None,Furniture
4,CUST01970,Customer_1970,customer1970@gmail.com,+91-7975175423,Female,1985-12-14,Jaipur,Student,BRONZE,21719.53,89,True,2020-05-17,2024-06-27,Toys
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2055,CUST01053,Customer_1053,customer1053@yahoo.com,+91-8474360862,Other,1995-09-26,Pune,Retired,Platinum,4557.69,166,False,2023-06-09,2024-01-09,Toys
2056,CUST01313,Customer_1313,customer1313@yahoo.com,+91-7981030211,Male,29-03-1991,Delhi,Retired,Gold,36453.86,6,True,2019-08-23,2024-11-17,Clothing
2057,CUST01746,Customer_1746,customer1746@gmail.com,+91-7448414485,Other,1964-03-07,Mumbai,Student,Platinum,25867.65,6,True,2020-07-20,2024-07-02,Electronics
2058,CUST01547,Customer_1547,customer1547@yahoo.com,+91-8279351106,Other,2002-04-19,Hyderabad,Student,Bronze,34135.15,61,True,2023-01-31,2024-10-20,Furniture
2059,CUST01919,Customer_1919,customer1919@yahoo.com,+91-9486568934,male,1973-04-16,Surat,Government Employee,Platinum,20523.74,132,False,2020-06-16,2024-09-19,Furniture

## Null values

In [9]:
df_cus[['email','phone','city','occupation','last_purchase_date']] = df_cus[['email','phone','city','occupation','last_purchase_date']].fillna('none')
df_cus.isnull().sum()

customer_id           0
full_name             0
email                 0
phone                 0
gender                0
date_of_birth         0
city                  0
occupation            0
membership_tier       0
lifetime_value        0
total_orders          0
is_active             0
joined_date           0
last_purchase_date    0
preferred_category    0
dtype: int64

In [10]:
df_cus['preferred_category'].unique()

array(['Sports', 'Electronics', 'Furniture', 'Toys', 'Groceries',
       'Clothing'], dtype=object)

## Date Formatting

In [11]:
cols = ['date_of_birth','joined_date','last_purchase_date']

df_cus[cols] = df_cus[cols].apply(
    lambda x: pd.to_datetime(x, format='mixed', errors='coerce')
)
# df_cus['last_purchase_date_display'] = (
#     df_cus['last_purchase_date']
#         .dt.strftime('%Y-%m-%d')
#         .fillna('None')
# )

In [12]:
# df_cus['last_purchase_date'] = df_cus['last_purchase_date'].fillna('none')
df_cus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2060 entries, 0 to 2059
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         2060 non-null   object
 1   full_name           2060 non-null   object
 2   email               2060 non-null   object
 3   phone               2060 non-null   object
 4   gender              2060 non-null   object
 5   date_of_birth       2060 non-null   datetime64[ns]
 6   city                2060 non-null   object
 7   occupation          2060 non-null   object
 8   membership_tier     2060 non-null   object
 9   lifetime_value      2060 non-null   object
 10  total_orders        2060 non-null   int64
 11  is_active           2060 non-null   bool
 12  joined_date         2060 non-null   datetime64[ns]
 13  last_purchase_date  1934 non-null   datetime64[ns]
 14  preferred_category  2060 non-null   object
dtypes: bool(1), datetime64[ns](3), int64(1), object(10)
memory usage: 227.4+ KB

## Remove Duplicate Values

In [13]:
print(df_cus['customer_id'].duplicated().sum())
print(df_cus['customer_id'].value_counts())

60
customer_id
CUST01029    2
CUST00951    2
CUST01010    2
CUST00343    2
CUST00527    2
            ..
CUST01475    1
CUST00062    1
CUST01495    1
CUST01828    1
CUST00388    1
Name: count, Length: 2000, dtype: int64

In [14]:
df_cus[df_cus['customer_id'].duplicated(keep=False)].sort_values('customer_id', ascending=False)

,customer_id,full_name,email,phone,gender,date_of_birth,city,occupation,membership_tier,lifetime_value,total_orders,is_active,joined_date,last_purchase_date,preferred_category
1612,CUST01987,Customer_1987,customer1987@yahoo.com,+91-7686490457,male,1976-10-14,Chennai,Doctor,Gold,$11832.92,71,True,2020-03-03,2024-11-18,Furniture
1435,CUST01987,Customer_1987,customer1987@yahoo.com,+91-7686490457,male,1976-10-14,Chennai,Doctor,Gold,$11832.92,71,True,2020-03-03,2024-11-18,Furniture
1692,CUST01939,Customer_1939,customer1939@yahoo.com,+91-7652232646,Male,1996-01-20,Jaipur,Teacher,Bronze,40061.94,172,True,2020-11-07,2024-08-10,Toys
620,CUST01939,Customer_1939,customer1939@yahoo.com,+91-7652232646,Male,1996-01-20,Jaipur,Teacher,Bronze,40061.94,172,True,2020-11-07,2024-08-10,Toys
861,CUST01920,Customer_1920,customer1920@gmail.com,+91-8434967858,Other,1992-09-25,Hyderabad,Business Owner,Platinum,34646.52,51,False,2023-02-15,2024-07-26,Clothing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,CUST00228,Customer_228,customer228@gmail.com,+91-9946285776,Female,1981-07-20,Hyderabad,Freelancer,Gold,33760.9,109,True,2020-05-17,2024-01-05,Clothing
1608,CUST00144,Customer_144,customer144@gmail.com,+91-9920296016,Female,2002-06-26,Delhi,Business Owner,Silver,22983.44,200,True,2019-06-22,2024-08-15,Furniture
1348,CUST00144,Customer_144,customer144@gmail.com,+91-9920296016,Female,2002-06-26,Delhi,Business Owner,Silver,22983.44,200,True,2019-06-22,2024-08-15,Furniture
169,CUST00086,Customer_86,customer86@gmail.com,+91-9334609324,female,1963-08-10,Delhi,Student,Silver,8986.73,57,False,2023-04-05,2024-12-25,Groceries
2013,CUST00086,Customer_86,customer86@gmail.com,+91-9334609324,female,1963-08-10,Delhi,Student,Silver,8986.73,57,False,2023-04-05,2024-12-25,Groceries

In [15]:
df_cus = df_cus.drop_duplicates(subset=['customer_id'], keep='first').reset_index(drop=True)
df_cus

,customer_id,full_name,email,phone,gender,date_of_birth,city,occupation,membership_tier,lifetime_value,total_orders,is_active,joined_date,last_purchase_date,preferred_category
0,CUST01100,Customer_1100,customer1100@gmail.com,+91-9042480121,Other,2001-05-04,Surat,Teacher,Gold,37700.71,56,False,2023-08-07,2024-07-29,Sports
1,CUST01694,Customer_1694,customer1694@gmail.com,+91-7298829927,Male,1983-01-12,Mumbai,Government Employee,Silver,34961.74,177,True,2020-08-23,2024-05-30,Sports
2,CUST00104,Customer_104,customer104@gmail.com,+91-9507694884,Male,1986-06-19,none,Business Owner,SILVER,35803.28,129,False,2021-09-29,2024-05-24,Electronics
3,CUST01532,Customer_1532,customer1532@gmail.com,+91-8485059977,Other,2001-05-14,Pune,Student,Platinum,35649.59,20,True,2019-09-02,NaT,Furniture
4,CUST01970,Customer_1970,customer1970@gmail.com,+91-7975175423,Female,1985-12-14,Jaipur,Student,BRONZE,21719.53,89,True,2020-05-17,2024-06-27,Toys
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST01053,Customer_1053,customer1053@yahoo.com,+91-8474360862,Other,1995-09-26,Pune,Retired,Platinum,4557.69,166,False,2023-06-09,2024-01-09,Toys
1996,CUST01313,Customer_1313,customer1313@yahoo.com,+91-7981030211,Male,1991-03-29,Delhi,Retired,Gold,36453.86,6,True,2019-08-23,2024-11-17,Clothing
1997,CUST01746,Customer_1746,customer1746@gmail.com,+91-7448414485,Other,1964-03-07,Mumbai,Student,Platinum,25867.65,6,True,2020-07-20,2024-07-02,Electronics
1998,CUST01547,Customer_1547,customer1547@yahoo.com,+91-8279351106,Other,2002-04-19,Hyderabad,Student,Bronze,34135.15,61,True,2023-01-31,2024-10-20,Furniture
1999,CUST01919,Customer_1919,customer1919@yahoo.com,+91-9486568934,male,1973-04-16,Surat,Government Employee,Platinum,20523.74,132,False,2020-06-16,2024-09-19,Furniture

In [16]:
print(df_cus['customer_id'].duplicated().sum())
df_cus[df_cus['customer_id'].duplicated(keep=False,)].sort_values('customer_id', ascending=False)

0

Empty DataFrame
Columns: [customer_id, full_name, email, phone, gender, date_of_birth, city, occupation, membership_tier, lifetime_value, total_orders, is_active, joined_date, last_purchase_date, preferred_category]
Index: []

In [17]:
df_cus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         2000 non-null   object
 1   full_name           2000 non-null   object
 2   email               2000 non-null   object
 3   phone               2000 non-null   object
 4   gender              2000 non-null   object
 5   date_of_birth       2000 non-null   datetime64[ns]
 6   city                2000 non-null   object
 7   occupation          2000 non-null   object
 8   membership_tier     2000 non-null   object
 9   lifetime_value      2000 non-null   object
 10  total_orders        2000 non-null   int64
 11  is_active           2000 non-null   bool
 12  joined_date         2000 non-null   datetime64[ns]
 13  last_purchase_date  1880 non-null   datetime64[ns]
 14  preferred_category  2000 non-null   object
dtypes: bool(1), datetime64[ns](3), int64(1), object(10)
memory usage: 220.8+ KB

## String Formatting

In [18]:
df_cus['membership_tier'].unique()

array(['Gold', 'Silver', 'SILVER', 'Platinum', 'BRONZE', 'PLATINUM',
       'Bronze', 'GOLD'], dtype=object)

In [19]:
df_cus[['gender','membership_tier']] = (
    df_cus[['gender','membership_tier']].apply(lambda x: x.str.title() )
)

In [20]:
df_cus['membership_tier'].unique()

array(['Gold', 'Silver', 'Platinum', 'Bronze'], dtype=object)

## Data Type conversion

In [21]:
df_cus['lifetime_value'] = df_cus['lifetime_value'].astype(str).str.replace(r'[^\d.]', '', regex=True)
print(df_cus['lifetime_value'][0:6])
print(df_cus['lifetime_value'].info())

0    37700.71
1    34961.74
2    35803.28
3    35649.59
4    21719.53
5    45186.68
Name: lifetime_value, dtype: object
<class 'pandas.core.series.Series'>
RangeIndex: 2000 entries, 0 to 1999
Series name: lifetime_value
Non-Null Count  Dtype
--------------  -----
2000 non-null   object
dtypes: object(1)
memory usage: 15.8+ KB
None

In [22]:
df_cus['lifetime_value'] = pd.to_numeric(df_cus['lifetime_value'], errors='coerce')

In [23]:
df_cus['lifetime_value'][0:3]
print(df_cus['lifetime_value'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 2000 entries, 0 to 1999
Series name: lifetime_value
Non-Null Count  Dtype
--------------  -----
2000 non-null   float64
dtypes: float64(1)
memory usage: 15.8 KB
None

In [24]:
df_cus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         2000 non-null   object
 1   full_name           2000 non-null   object
 2   email               2000 non-null   object
 3   phone               2000 non-null   object
 4   gender              2000 non-null   object
 5   date_of_birth       2000 non-null   datetime64[ns]
 6   city                2000 non-null   object
 7   occupation          2000 non-null   object
 8   membership_tier     2000 non-null   object
 9   lifetime_value      2000 non-null   float64
 10  total_orders        2000 non-null   int64
 11  is_active           2000 non-null   bool
 12  joined_date         2000 non-null   datetime64[ns]
 13  last_purchase_date  1880 non-null   datetime64[ns]
 14  preferred_category  2000 non-null   object
dtypes: bool(1), datetime64[ns](3), float64(1), int64(1), object(9)
memory usage: 220.8+ KB

In [25]:
df_cus

,customer_id,full_name,email,phone,gender,date_of_birth,city,occupation,membership_tier,lifetime_value,total_orders,is_active,joined_date,last_purchase_date,preferred_category
0,CUST01100,Customer_1100,customer1100@gmail.com,+91-9042480121,Other,2001-05-04,Surat,Teacher,Gold,37700.71,56,False,2023-08-07,2024-07-29,Sports
1,CUST01694,Customer_1694,customer1694@gmail.com,+91-7298829927,Male,1983-01-12,Mumbai,Government Employee,Silver,34961.74,177,True,2020-08-23,2024-05-30,Sports
2,CUST00104,Customer_104,customer104@gmail.com,+91-9507694884,Male,1986-06-19,none,Business Owner,Silver,35803.28,129,False,2021-09-29,2024-05-24,Electronics
3,CUST01532,Customer_1532,customer1532@gmail.com,+91-8485059977,Other,2001-05-14,Pune,Student,Platinum,35649.59,20,True,2019-09-02,NaT,Furniture
4,CUST01970,Customer_1970,customer1970@gmail.com,+91-7975175423,Female,1985-12-14,Jaipur,Student,Bronze,21719.53,89,True,2020-05-17,2024-06-27,Toys
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST01053,Customer_1053,customer1053@yahoo.com,+91-8474360862,Other,1995-09-26,Pune,Retired,Platinum,4557.69,166,False,2023-06-09,2024-01-09,Toys
1996,CUST01313,Customer_1313,customer1313@yahoo.com,+91-7981030211,Male,1991-03-29,Delhi,Retired,Gold,36453.86,6,True,2019-08-23,2024-11-17,Clothing
1997,CUST01746,Customer_1746,customer1746@gmail.com,+91-7448414485,Other,1964-03-07,Mumbai,Student,Platinum,25867.65,6,True,2020-07-20,2024-07-02,Electronics
1998,CUST01547,Customer_1547,customer1547@yahoo.com,+91-8279351106,Other,2002-04-19,Hyderabad,Student,Bronze,34135.15,61,True,2023-01-31,2024-10-20,Furniture
1999,CUST01919,Customer_1919,customer1919@yahoo.com,+91-9486568934,Male,1973-04-16,Surat,Government Employee,Platinum,20523.74,132,False,2020-06-16,2024-09-19,Furniture

## Saving the Processed Data

In [ ]:
df_cus.to_csv("../data/processed/processed_customer_data.csv",index=False)

In [ ]:
df_c = pd.read_csv(r"../data/processed/processed_customer_data.csv")
df_c[0:10]

,customer_id,full_name,email,phone,gender,date_of_birth,city,occupation,membership_tier,lifetime_value,total_orders,is_active,joined_date,last_purchase_date,preferred_category
0,CUST01100,Customer_1100,customer1100@gmail.com,+91-9042480121,Other,2001-05-04,Surat,Teacher,Gold,37700.71,56,False,2023-08-07,2024-07-29,Sports
1,CUST01694,Customer_1694,customer1694@gmail.com,+91-7298829927,Male,1983-01-12,Mumbai,Government Employee,Silver,34961.74,177,True,2020-08-23,2024-05-30,Sports
2,CUST00104,Customer_104,customer104@gmail.com,+91-9507694884,Male,1986-06-19,none,Business Owner,Silver,35803.28,129,False,2021-09-29,2024-05-24,Electronics
3,CUST01532,Customer_1532,customer1532@gmail.com,+91-8485059977,Other,2001-05-14,Pune,Student,Platinum,35649.59,20,True,2019-09-02,NaN,Furniture
4,CUST01970,Customer_1970,customer1970@gmail.com,+91-7975175423,Female,1985-12-14,Jaipur,Student,Bronze,21719.53,89,True,2020-05-17,2024-06-27,Toys
5,CUST00802,Customer_802,customer802@gmail.com,+91-9548886614,Male,1969-10-05,Delhi,Teacher,Platinum,45186.68,116,False,2023-07-18,2024-10-12,Toys
6,CUST01431,Customer_1431,customer1431@yahoo.com,+91-8837782194,Male,2000-09-12,Bangalore,Teacher,Gold,8573.01,83,True,2019-07-10,2024-12-04,Toys
7,CUST00781,Customer_781,customer781@yahoo.com,+91-9681184477,Male,1993-06-24,Surat,Freelancer,Gold,10350.63,13,True,2021-10-12,2024-04-08,Toys
8,CUST01231,Customer_1231,customer1231@yahoo.com,+91-8408654725,Other,1995-12-03,Kolkata,Engineer,Silver,24147.76,154,True,2020-09-17,2024-12-25,Groceries
9,CUST01678,Customer_1678,customer1678@gmail.com,+91-9744517243,Other,2003-02-13,Hyderabad,Freelancer,Platinum,18134.28,89,True,2020-09-02,2024-09-17,Toys

In [28]:
df_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         2000 non-null   object
 1   full_name           2000 non-null   object
 2   email               2000 non-null   object
 3   phone               2000 non-null   object
 4   gender              2000 non-null   object
 5   date_of_birth       2000 non-null   object
 6   city                2000 non-null   object
 7   occupation          2000 non-null   object
 8   membership_tier     2000 non-null   object
 9   lifetime_value      2000 non-null   float64
 10  total_orders        2000 non-null   int64
 11  is_active           2000 non-null   bool
 12  joined_date         2000 non-null   object
 13  last_purchase_date  1880 non-null   object
 14  preferred_category  2000 non-null   object
dtypes: bool(1), float64(1), int64(1), object(12)
memory usage: 220.8+ KB