In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', 20)

In [ ]:
df_trans = pd.read_csv(r"../data/raw/sales_data.csv")
df_trans

,transaction_id,store_id,region,category,product_name,quantity,unit_price,total_amount,payment_mode,sale_date,sales_rep_id,discount_pct
0,TXN01134,NaN,North,Furniture,Bed Frame,30.0,222.69,6680.70,UPI,2024-08-09,REP007,12.0
1,TXN01159,STORE_002,West,Toys,Board Game,20.0,391.69,7833.80,Debit Card,03/12/2024,REP002,8.2
2,TXN01704,STORE_004,South,Sports,Dumbbells,19.0,1098.14,20864.66,Credit Card,2024-01-09,REP007,18.1
3,TXN00521,STORE_003,South,Groceries,Tea,17.0,378.37,6432.29,Debit Card,2024-08-29,REP020,10.3
4,TXN01645,STORE_001,East,Sports,Yoga Mat,34.0,212.11,7211.74,Net Banking,2024-12-06,REP006,22.2
...,...,...,...,...,...,...,...,...,...,...,...,...
2055,TXN01145,STORE_005,North,Groceries,Pasta,13.0,1943.63,25267.19,Debit Card,2024-07-05,REP001,9.1
2056,TXN00049,STORE_004,West,Toys,Puzzle,36.0,258.94,9321.84,Credit Card,2024-11-11,REP019,9.0
2057,TXN00773,NaN,Central,GROCERIES,Tea,22.0,1619.92,35638.24,Cash,2024-01-17,REP014,26.4
2058,TXN01849,STORE_005,Central,Furniture,Sofa,36.0,260.17,9366.12,Cash,05/05/2024,REP013,10.0
2059,TXN01232,STORE_002,east,Groceries,Tea,22.0,921.67,20276.74,Debit Card,2024-07-20,REP003,27.5

In [3]:
df_trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2060 entries, 0 to 2059
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  2060 non-null   object
 1   store_id        1933 non-null   object
 2   region          2060 non-null   object
 3   category        2060 non-null   object
 4   product_name    1935 non-null   object
 5   quantity        2060 non-null   float64
 6   unit_price      1915 non-null   float64
 7   total_amount    2060 non-null   float64
 8   payment_mode    1922 non-null   object
 9   sale_date       2060 non-null   object
 10  sales_rep_id    1955 non-null   object
 11  discount_pct    2060 non-null   float64
dtypes: float64(4), object(8)
memory usage: 193.2+ KB

## Null values

In [4]:
df_trans.isnull().sum()        # column-wise count
# df_trans.isnull().sum().sum()  # total missing

transaction_id      0
store_id          127
region              0
category            0
product_name      125
quantity            0
unit_price        145
total_amount        0
payment_mode      138
sale_date           0
sales_rep_id      105
discount_pct        0
dtype: int64

In [5]:
df_trans[['store_id','product_name','payment_mode','sales_rep_id']] = df_trans[['store_id','product_name','payment_mode','sales_rep_id']].fillna("unknown")
df_trans.isnull().sum()

transaction_id      0
store_id            0
region              0
category            0
product_name        0
quantity            0
unit_price        145
total_amount        0
payment_mode        0
sale_date           0
sales_rep_id        0
discount_pct        0
dtype: int64

## Filling Unit_Price Values

In [6]:
df_trans['unit_price'] = df_trans['unit_price'].fillna(df_trans['total_amount']/df_trans['quantity'])

In [7]:
# df_trans['product_name'] = df_trans['product_name'].fillna(0)
# df_trans.isnull().sum()

## Date Formatting

In [8]:
df_trans['sale_date'] = pd.to_datetime(df_trans['sale_date'],format='mixed', errors='coerce')
df_trans

,transaction_id,store_id,region,category,product_name,quantity,unit_price,total_amount,payment_mode,sale_date,sales_rep_id,discount_pct
0,TXN01134,unknown,North,Furniture,Bed Frame,30.0,222.69,6680.70,UPI,2024-08-09,REP007,12.0
1,TXN01159,STORE_002,West,Toys,Board Game,20.0,391.69,7833.80,Debit Card,2024-03-12,REP002,8.2
2,TXN01704,STORE_004,South,Sports,Dumbbells,19.0,1098.14,20864.66,Credit Card,2024-01-09,REP007,18.1
3,TXN00521,STORE_003,South,Groceries,Tea,17.0,378.37,6432.29,Debit Card,2024-08-29,REP020,10.3
4,TXN01645,STORE_001,East,Sports,Yoga Mat,34.0,212.11,7211.74,Net Banking,2024-12-06,REP006,22.2
...,...,...,...,...,...,...,...,...,...,...,...,...
2055,TXN01145,STORE_005,North,Groceries,Pasta,13.0,1943.63,25267.19,Debit Card,2024-07-05,REP001,9.1
2056,TXN00049,STORE_004,West,Toys,Puzzle,36.0,258.94,9321.84,Credit Card,2024-11-11,REP019,9.0
2057,TXN00773,unknown,Central,GROCERIES,Tea,22.0,1619.92,35638.24,Cash,2024-01-17,REP014,26.4
2058,TXN01849,STORE_005,Central,Furniture,Sofa,36.0,260.17,9366.12,Cash,2024-05-05,REP013,10.0
2059,TXN01232,STORE_002,east,Groceries,Tea,22.0,921.67,20276.74,Debit Card,2024-07-20,REP003,27.5

In [9]:
df_trans.isnull().sum()

transaction_id    0
store_id          0
region            0
category          0
product_name      0
quantity          0
unit_price        0
total_amount      0
payment_mode      0
sale_date         0
sales_rep_id      0
discount_pct      0
dtype: int64

## Remove Duplicate Values

In [10]:
print(df_trans['transaction_id'].duplicated().sum())
print(df_trans['transaction_id'].value_counts())

60
transaction_id
TXN01546    2
TXN00351    2
TXN00695    2
TXN00238    2
TXN01505    2
           ..
TXN01340    1
TXN00597    1
TXN00999    1
TXN01263    1
TXN00305    1
Name: count, Length: 2000, dtype: int64

In [11]:
df_trans[df_trans['transaction_id'].duplicated(keep=False)].sort_values('transaction_id', ascending=False)

,transaction_id,store_id,region,category,product_name,quantity,unit_price,total_amount,payment_mode,sale_date,sales_rep_id,discount_pct
891,TXN01927,STORE_004,East,Sports,Yoga Mat,16.0,1598.61,25577.76,Cash,2024-01-09,REP020,8.0
2009,TXN01927,STORE_004,east,Sports,Yoga Mat,16.0,1598.61,25577.76,Cash,2024-01-09,REP020,8.0
1896,TXN01913,STORE_002,East,Sports,Yoga Mat,26.0,1288.88,33510.88,Cash,2024-12-22,REP009,26.5
159,TXN01913,STORE_002,East,Sports,Yoga Mat,26.0,1288.88,33510.88,Cash,2024-12-22,REP009,26.5
1237,TXN01892,STORE_005,North,Electronics,Smartwatch,19.0,617.66,11735.54,Credit Card,2024-10-23,REP011,1.4
...,...,...,...,...,...,...,...,...,...,...,...,...
1430,TXN00111,STORE_001,West,Furniture,Chair,44.0,1095.46,48200.24,Debit Card,2024-10-27,REP010,19.2
1194,TXN00109,unknown,South,Furniture,Bed Frame,44.0,1586.08,69787.52,Cash,2024-11-08,REP013,18.6
1363,TXN00109,unknown,South,FURNITURE,Bed Frame,44.0,1586.08,69787.52,Cash,2024-11-08,REP013,18.6
1329,TXN00003,STORE_005,East,Toys,Remote Car,27.0,444.78,12009.06,Cash,2024-03-22,REP014,10.2
1854,TXN00003,STORE_005,East,Toys,Remote Car,27.0,444.78,12009.06,Cash,2024-03-22,REP014,10.2

In [12]:
df_trans.groupby('transaction_id').filter(lambda x: len(x) > 1).sort_values('transaction_id', ascending=False)

,transaction_id,store_id,region,category,product_name,quantity,unit_price,total_amount,payment_mode,sale_date,sales_rep_id,discount_pct
891,TXN01927,STORE_004,East,Sports,Yoga Mat,16.0,1598.61,25577.76,Cash,2024-01-09,REP020,8.0
2009,TXN01927,STORE_004,east,Sports,Yoga Mat,16.0,1598.61,25577.76,Cash,2024-01-09,REP020,8.0
1896,TXN01913,STORE_002,East,Sports,Yoga Mat,26.0,1288.88,33510.88,Cash,2024-12-22,REP009,26.5
159,TXN01913,STORE_002,East,Sports,Yoga Mat,26.0,1288.88,33510.88,Cash,2024-12-22,REP009,26.5
1237,TXN01892,STORE_005,North,Electronics,Smartwatch,19.0,617.66,11735.54,Credit Card,2024-10-23,REP011,1.4
...,...,...,...,...,...,...,...,...,...,...,...,...
1430,TXN00111,STORE_001,West,Furniture,Chair,44.0,1095.46,48200.24,Debit Card,2024-10-27,REP010,19.2
1194,TXN00109,unknown,South,Furniture,Bed Frame,44.0,1586.08,69787.52,Cash,2024-11-08,REP013,18.6
1363,TXN00109,unknown,South,FURNITURE,Bed Frame,44.0,1586.08,69787.52,Cash,2024-11-08,REP013,18.6
1329,TXN00003,STORE_005,East,Toys,Remote Car,27.0,444.78,12009.06,Cash,2024-03-22,REP014,10.2
1854,TXN00003,STORE_005,East,Toys,Remote Car,27.0,444.78,12009.06,Cash,2024-03-22,REP014,10.2

In [13]:
df_trans = df_trans.drop_duplicates(subset=['transaction_id'], keep='first').reset_index(drop=True)
df_trans

,transaction_id,store_id,region,category,product_name,quantity,unit_price,total_amount,payment_mode,sale_date,sales_rep_id,discount_pct
0,TXN01134,unknown,North,Furniture,Bed Frame,30.0,222.69,6680.70,UPI,2024-08-09,REP007,12.0
1,TXN01159,STORE_002,West,Toys,Board Game,20.0,391.69,7833.80,Debit Card,2024-03-12,REP002,8.2
2,TXN01704,STORE_004,South,Sports,Dumbbells,19.0,1098.14,20864.66,Credit Card,2024-01-09,REP007,18.1
3,TXN00521,STORE_003,South,Groceries,Tea,17.0,378.37,6432.29,Debit Card,2024-08-29,REP020,10.3
4,TXN01645,STORE_001,East,Sports,Yoga Mat,34.0,212.11,7211.74,Net Banking,2024-12-06,REP006,22.2
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,TXN01145,STORE_005,North,Groceries,Pasta,13.0,1943.63,25267.19,Debit Card,2024-07-05,REP001,9.1
1996,TXN00049,STORE_004,West,Toys,Puzzle,36.0,258.94,9321.84,Credit Card,2024-11-11,REP019,9.0
1997,TXN00773,unknown,Central,GROCERIES,Tea,22.0,1619.92,35638.24,Cash,2024-01-17,REP014,26.4
1998,TXN01849,STORE_005,Central,Furniture,Sofa,36.0,260.17,9366.12,Cash,2024-05-05,REP013,10.0
1999,TXN01232,STORE_002,east,Groceries,Tea,22.0,921.67,20276.74,Debit Card,2024-07-20,REP003,27.5

In [14]:
df_trans[df_trans['transaction_id'].duplicated(keep=False,)].sort_values('transaction_id', ascending=False)

Empty DataFrame
Columns: [transaction_id, store_id, region, category, product_name, quantity, unit_price, total_amount, payment_mode, sale_date, sales_rep_id, discount_pct]
Index: []

## String Formatting

In [15]:
df_trans['region'].unique()

array(['North', 'West', 'South', 'East', 'Central', 'south', 'central',
       'north', 'east', 'west'], dtype=object)

In [16]:
df_trans[['region','category','product_name']] = (
    df_trans[['region','category','product_name']].apply(lambda x: x.str.title() if isinstance(x, str) else x)
)

In [17]:
df_trans['region'].unique()

array(['North', 'West', 'South', 'East', 'Central', 'south', 'central',
       'north', 'east', 'west'], dtype=object)

In [18]:
df_trans

,transaction_id,store_id,region,category,product_name,quantity,unit_price,total_amount,payment_mode,sale_date,sales_rep_id,discount_pct
0,TXN01134,unknown,North,Furniture,Bed Frame,30.0,222.69,6680.70,UPI,2024-08-09,REP007,12.0
1,TXN01159,STORE_002,West,Toys,Board Game,20.0,391.69,7833.80,Debit Card,2024-03-12,REP002,8.2
2,TXN01704,STORE_004,South,Sports,Dumbbells,19.0,1098.14,20864.66,Credit Card,2024-01-09,REP007,18.1
3,TXN00521,STORE_003,South,Groceries,Tea,17.0,378.37,6432.29,Debit Card,2024-08-29,REP020,10.3
4,TXN01645,STORE_001,East,Sports,Yoga Mat,34.0,212.11,7211.74,Net Banking,2024-12-06,REP006,22.2
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,TXN01145,STORE_005,North,Groceries,Pasta,13.0,1943.63,25267.19,Debit Card,2024-07-05,REP001,9.1
1996,TXN00049,STORE_004,West,Toys,Puzzle,36.0,258.94,9321.84,Credit Card,2024-11-11,REP019,9.0
1997,TXN00773,unknown,Central,GROCERIES,Tea,22.0,1619.92,35638.24,Cash,2024-01-17,REP014,26.4
1998,TXN01849,STORE_005,Central,Furniture,Sofa,36.0,260.17,9366.12,Cash,2024-05-05,REP013,10.0
1999,TXN01232,STORE_002,east,Groceries,Tea,22.0,921.67,20276.74,Debit Card,2024-07-20,REP003,27.5

## Checking the values

In [19]:
df_trans['unit_price'] = df_trans['unit_price'].abs()
df_trans[~np.isclose(df_trans['unit_price'] * df_trans['quantity'], df_trans['total_amount'])]

Empty DataFrame
Columns: [transaction_id, store_id, region, category, product_name, quantity, unit_price, total_amount, payment_mode, sale_date, sales_rep_id, discount_pct]
Index: []

In [20]:
df_trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  2000 non-null   object
 1   store_id        2000 non-null   object
 2   region          2000 non-null   object
 3   category        2000 non-null   object
 4   product_name    2000 non-null   object
 5   quantity        2000 non-null   float64
 6   unit_price      2000 non-null   float64
 7   total_amount    2000 non-null   float64
 8   payment_mode    2000 non-null   object
 9   sale_date       2000 non-null   datetime64[ns]
 10  sales_rep_id    2000 non-null   object
 11  discount_pct    2000 non-null   float64
dtypes: datetime64[ns](1), float64(4), object(7)
memory usage: 187.6+ KB

In [21]:
df_trans.isnull().sum()

transaction_id    0
store_id          0
region            0
category          0
product_name      0
quantity          0
unit_price        0
total_amount      0
payment_mode      0
sale_date         0
sales_rep_id      0
discount_pct      0
dtype: int64

In [22]:
df_trans

,transaction_id,store_id,region,category,product_name,quantity,unit_price,total_amount,payment_mode,sale_date,sales_rep_id,discount_pct
0,TXN01134,unknown,North,Furniture,Bed Frame,30.0,222.69,6680.70,UPI,2024-08-09,REP007,12.0
1,TXN01159,STORE_002,West,Toys,Board Game,20.0,391.69,7833.80,Debit Card,2024-03-12,REP002,8.2
2,TXN01704,STORE_004,South,Sports,Dumbbells,19.0,1098.14,20864.66,Credit Card,2024-01-09,REP007,18.1
3,TXN00521,STORE_003,South,Groceries,Tea,17.0,378.37,6432.29,Debit Card,2024-08-29,REP020,10.3
4,TXN01645,STORE_001,East,Sports,Yoga Mat,34.0,212.11,7211.74,Net Banking,2024-12-06,REP006,22.2
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,TXN01145,STORE_005,North,Groceries,Pasta,13.0,1943.63,25267.19,Debit Card,2024-07-05,REP001,9.1
1996,TXN00049,STORE_004,West,Toys,Puzzle,36.0,258.94,9321.84,Credit Card,2024-11-11,REP019,9.0
1997,TXN00773,unknown,Central,GROCERIES,Tea,22.0,1619.92,35638.24,Cash,2024-01-17,REP014,26.4
1998,TXN01849,STORE_005,Central,Furniture,Sofa,36.0,260.17,9366.12,Cash,2024-05-05,REP013,10.0
1999,TXN01232,STORE_002,east,Groceries,Tea,22.0,921.67,20276.74,Debit Card,2024-07-20,REP003,27.5

## Saving the Processed Data

In [ ]:
df_trans.to_csv("../data/processed/processed_sales_data.csv",index=False)

In [ ]:
df_sal = pd.read_csv(r"../data/processed/processed_sales_data.csv")
df_sal

,transaction_id,store_id,region,category,product_name,quantity,unit_price,total_amount,payment_mode,sale_date,sales_rep_id,discount_pct
0,TXN01134,unknown,North,Furniture,Bed Frame,30.0,222.69,6680.70,UPI,2024-08-09,REP007,12.0
1,TXN01159,STORE_002,West,Toys,Board Game,20.0,391.69,7833.80,Debit Card,2024-03-12,REP002,8.2
2,TXN01704,STORE_004,South,Sports,Dumbbells,19.0,1098.14,20864.66,Credit Card,2024-01-09,REP007,18.1
3,TXN00521,STORE_003,South,Groceries,Tea,17.0,378.37,6432.29,Debit Card,2024-08-29,REP020,10.3
4,TXN01645,STORE_001,East,Sports,Yoga Mat,34.0,212.11,7211.74,Net Banking,2024-12-06,REP006,22.2
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,TXN01145,STORE_005,North,Groceries,Pasta,13.0,1943.63,25267.19,Debit Card,2024-07-05,REP001,9.1
1996,TXN00049,STORE_004,West,Toys,Puzzle,36.0,258.94,9321.84,Credit Card,2024-11-11,REP019,9.0
1997,TXN00773,unknown,Central,GROCERIES,Tea,22.0,1619.92,35638.24,Cash,2024-01-17,REP014,26.4
1998,TXN01849,STORE_005,Central,Furniture,Sofa,36.0,260.17,9366.12,Cash,2024-05-05,REP013,10.0
1999,TXN01232,STORE_002,east,Groceries,Tea,22.0,921.67,20276.74,Debit Card,2024-07-20,REP003,27.5